project/app/urls.py
from . import views
from django.urls import path

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup_view, name='signup'),
    path('title', views.title, name='title'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('user', views.user_view, name='user'),
    path('other', views.other_view, name='other'),
    path('howToPlay',views.HowToPlay, name='howToPlay'),
    path('diffsec', views.Diffsec, name='diffsec'),
    path('gameEasy',views.gameEasy, name='gameEasy'),
    path('gameNormal',views.gameNormal,name='gameNormal'),
    path('gameHard',views.gameHard,name='gameHard'),
    path('ajax', views.get_data, name='get_data'),
    path('savedata',views.save_data, name='save_data'),
    path('training',views.move_balance,name='training'),
    path('ranking',views.move_ranking,name='ranking'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app.urls')),
]

project/templates/Difficulty-Selection.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>難易度選択</title>
        <meta name="description" content="GeekTouchTyper">
        <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    </head>
    <body>
        <header>
            <h1>Geek Touch Typer</h1>
        </header>
        {% comment %} <form>
            {% csrf_token%}
            <input class = "back-button" type="button" value="タイトル画面に戻る" onClick="history.back()">
        </form> {% endcomment %}
        <input class = "back-button" type="button" onClick="link_origin()" value="タイトル画面に戻る" >
        <div class="box-container">
            <img src="static/img/mitechan_selection.png" alt="みてちゃん" class="mite">
            <div class="container">
                <div class="difficulty-buttons">
                    <input class = "button" type="button" onclick="link_easy()" value="Easy">
                    <p class="difficulty-description">簡単なレベルでゲームを楽しめます。</p>
                </div>

                <div class="difficulty-buttons">
                    <input class = "button" type="button" onclick="link_normal()" value="Normal">
                    <p class="difficulty-description">通常のレベルでゲームを楽しめます。</p>
                </div>

                <div class="difficulty-buttons">
                    <input class = "button" type="button" onclick="link_hard()" value="Hard">
                    <p class="difficulty-description">難しいレベルでゲームを楽しめます。</p>
                </div>
            </div>
        </div>
        <footer>
            <p>Produced by MML</p>
        </footer>
        <script>

            let query = location.search;
            let value = query.split('=');

            let temp = value[1]

            function link_easy()
            {
                location.href = "{% url 'app:gameEasy' %}" + "?name=" + encodeURIComponent(temp);
            }

            function link_normal()
            {
                location.href = "{% url 'app:gameNormal' %}" + "?name=" + encodeURIComponent(temp);
            }

            function link_hard()
            {
                location.href = "{% url 'app:gameHard' %}" + "?name=" + encodeURIComponent(temp);
            }

            function link_origin()
            {
                location.href = "{% url 'app:title' %}"  + "?name=" + encodeURIComponent(temp);
            }
        </script>
    </body>
</html>

project/templates/How-to-Play.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Geek Touch Typer</title>
        {% comment %} <meta name="description" content="GeekTouchTyper"> {% endcomment %}
        <link rel="stylesheet" href="{% static 'css/style3.css' %}"/>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <div>
                <h1>遊び方</h1>
                <div class="box-play">
                    <ol>
                        <li>
                            プレイ前に視線検知のための調整を行います。
                            該当ページに記載の指示に従って調整を行ってください。
                        </li>
                        <li>
                            次にプレイするゲームの難易度を選択します。
                            「簡単」「通常」「難しい」の3つのレベルからお好きなものを選択してください。
                        </li>
                        <li>
                            その後ゲームをプレイできます。
                            タイピングミスやキーボードを見ると右上にあるハートが減り、ハートが0になるとGame Overとなります。
                            プレイ中はカメラの中央に顔が来るように注意してください。
                            また、プレイ中はツンデレキャラクターのみてちゃんが反応してくれます。
                        </li>
                        <li>
                            Game Clear後はスコアが表示されます。
                            スコアはミス回数とClear時間に応じて算出されます。
                            また、難易度が高いほど獲得できる最大スコアが大きくなりますが、その代わりにClearが難しくなります。
                            高スコアを目指して頑張ってください！
                        </li>
                    </ol>
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
    </body>
</html>

project/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Geek Touch Typer</title>
        <meta name="description" content="GeekTouchTyper">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <div class="box-container">
                <img src="static/img/mitechan_index.png" alt="みてちゃん" class="mite">
                <div class="box">
                    <div class="description">
                        <p>既にユーザー登録済みの人はこちら</p>
                    </div>
                    <input class="button" type="button" onclick="link1()" value="ログイン">
                    <div class="separator"></div>
                    <div class="description">
                        <p>まだユーザー登録をしていない人はこちら</p>
                    </div>
                    <input class = "button" type="button" onclick="link2()" value="新規登録">
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
    </body>
    <script>
        function link1() {
        location.href ="{% url 'app:login' %}";
        }
        function link2() {
        location.href ="{% url 'app:signup' %}";
        }
    </script>
</html>

project/templates/login.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>ログイン</title>
        <meta name="description" content="GeekTouchTyper">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <div class="box-container">
                <img src="static/img/mitechan_login.png" alt="みてちゃん" class="mite">
                <div class="box">
                    <h2>ログイン</h2>
                    <form action="{% url 'app:login'%}" method="post">
                    {% csrf_token %}
                        <p>{{ form.username|add_class:'username' }}</p>
                        <p>{{ form.password|add_class:'password' }}</p>
                        <p><input type="hidden" name="next" value="{{next}}"></p>
                        <p><input class="button" type="submit" value="ログイン"></p>
                    </form>
                    <div id="description">アカウントがない人はこちら：<a href="{% url 'app:signup'%}">新規登録</a></div>
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
    </body>
</html>

project/templates/other.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>他のユーザーの情報</title>
</head>
<body>
    <h1>他のユーザーの情報</h1>
    {% for user in users %}
    <h2>{{user.username}}</h2>
    <!-- <p>連絡先：{{user.email}}</p> -->
    {% endfor %}
    <p><a href="{% url 'user'%}">あなたの情報</a></p>
    <p><a href="{% url 'logout'%}">ログアウト</a></p>
</body>

</html>

project/templates/ranking.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        {% comment %} <title>ランキング</title> {% endcomment %}
        <link rel="stylesheet" href="{% static 'css/style4.css' %}">
    </head>
    <body>
        <p class="score">スコアランキング</p>
        <div class="container">
            <input class = "back-button" type="button" value="タイトル画面に戻る" onClick="history.back()">
        </div>
        <div>
            <img src="static/img/mitechan_ranking1.png" alt="みてちゃん" class="back-girl-1">
            <img src="static/img/mitechan_ranking2.png" alt="みてちゃん" class="back-girl-2">
            <table>
                <tr>
                    <th>順位</th>
                    <th>名前</th>
                    <th>スコア</th>
                    </tr>
                <tr>
                    <th id = class_1></th>
                    <th id = class_1_name></th>
                    <th id = class_1_score></th>
                </tr>
                <tr>
                    <th id = class_2></th>
                    <th id = class_2_name></th>
                    <th id = class_2_score></th>
                </tr>
                <tr>
                    <th id = class_3></th>
                    <th id = class_3_name></th>
                    <th id = class_3_score></th>
                </tr>
                <tr>
                    <th id = class_4></th>
                    <th id = class_4_name></th>
                    <th id = class_4_score></th>
                </tr>
                <tr>
                    <th id = class_5></th>
                    <th id = class_5_name></th>
                    <th id = class_5_score></th>
                </tr>
                <tr>
                    <th id = class_6></th>
                    <th id = class_6_name></th>
                    <th id = class_6_score></th>
                </tr>
                <tr>
                    <th id = class_7></th>
                    <th id = class_7_name></th>
                    <th id = class_7_score></th>
                </tr>
                <tr>
                    <th id = class_8></th>
                    <th id = class_8_name></th>
                    <th id = class_8_score></th>
                </tr>
                <tr>
                    <th id = class_9></th>
                    <th id = class_9_name></th>
                    <th id = class_9_score></th>
                </tr>
                <tr>
                    <th id = class_10></th>
                    <th id = class_10_name></th>
                    <th id = class_10_score></th>
                </tr>
            </table>
        </div>

        <script>

            var datas = []
            let tmp = []
            {% for ranking_data in ranking_list %}
                tmp = ["{{ranking_data.name}}", "{{ranking_data.score}}"]
                console.log(tmp)
                datas.push(tmp)
            {% endfor %}

            datas.sort( (a, b) => {
                return  b[b.length -1] - a[a.length - 1]
            })

            var maxLen = datas.length;

            var ranking = []
            for(let j = 0; j < 10; j++)
            {
                if(maxLen < j+1)
                {
                    document.getElementById("class_" + (j+1)).innerHTML = j+1;
                    document.getElementById("class_" + (j+1) + "_name").innerHTML = "なし";
                    document.getElementById("class_" + (j+1) + "_score").innerHTML = "なし";
                }
                else
                {
                    document.getElementById("class_" + (j+1)).innerHTML = j+1;
                    document.getElementById("class_" + (j+1) + "_name").innerHTML = datas[j][0];
                    document.getElementById("class_" + (j+1) + "_score").innerHTML = datas[j][1];
                }
            }

        </script>
    </body>
</html>

project/templates/signup.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>ユーザー登録</title>
        <meta name="description" content="GeekTouchTyper">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <div class="box-container">
                <img src="static/img/mitechan_signup.png" alt="みてちゃん" class="mite">
                <div class="box-signup">
                    <h2>ユーザー登録</h2>
                    <form action="{% url 'app:signup' %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                            <p><small style="color: grey">{{ field.help_text }}</small></p>
                            <br>
                            {% endif %}
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                        {% endfor %}
                        <p><input class="button" type="submit" onclick="link()" value="登録"></p>
                    </form>
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
    </body>
    <script>
        function link()
        {
            location.href = "{% url 'app:title' %}";
        }
    </script>
</html>

project/templates/title.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>ホーム</title>
        <meta name="description" content="GeekTouchTyper">
        <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <div class="box-container">
                <img src="static/img/mitechan_title.png" alt="みてちゃん" class="mite">
                <div class="box">
                    <p><input class = "button" type="button" onclick="link1()" value="プレイ"></p>
                    <p><input class = "button" type="button" onclick="link2()" value="遊び方"></p>
                    <p><input class = "button" type="button" onclick="ranking()" value="ランキング"></p>
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
        <script>
            function link1()
            {
                let temp = "{{user.username}}"
                location.href ="{% url 'app:training' %}" + "?name=" + encodeURIComponent(temp);
            }
            function link2()
            {
                location.href ="{% url 'app:howToPlay' %}";
            }
            function ranking()
            {
                let temp = "{{user.username}}"
                location.href ="{% url 'app:ranking' %}" + "?name=" + encodeURIComponent(temp);
            }
        </script>
    </body>
</html>

project/templates/training.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>test</title>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js "></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
        <script src="https://docs.opencv.org/4.5.5/opencv.js"></script>
        <link rel="stylesheet" href="{% static 'css/style3.css' %}"/>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Geek Touch Typer</h1>
            </header>
            <form>
                {% csrf_token%}
                <input class = "back-button" type="button" value="タイトル画面に戻る" onClick="history.back()">
            </form>
            <div class="display-none">
                {% csrf_token %}
                <canvas id="canvas"> </canvas>
                <img id="image"> </img>
            </div>
            <div class="box-container">
                <div class="box">
                    <div class="box-h1">
                        <h1>調整方法</h1>
                    </div>
                    <div class="box-description">
                        <ol>
                            <li>
                                はじめに画面を見ているときの顔画像を送信します。
                                顔が画像の中央に来るようにした状態で、「画像送信」ボタンを見ながら6回ゆっくりとクリックしてください。
                            </li>
                            <li>
                                次にキーボードを見ているときの顔画像を送信します。
                                顔が画像の中央に来るようにした状態で、キーボードを見ながら任意のキーを6回ゆっくりと押してください。
                            </li>
                            <li>
                                その後「調整開始」ボタンが押せるようになるので、ボタンを押して調整を開始します。
                            </li>
                            <li>
                                調整が終了すると「難易度選択へ」のボタンが現れるので、ボタンをクリックして難易度選択ページに移動します。
                            </li>
                        </ol>
                    </div>
                </div>
                <div class="send">
                    <div>
                        <input class = "button" type="button" value="画像送信" id="send_button">
                    </div>
                    <div>
                        <video id="video" width="320" height="240" autoplay></video>
                    </div>
                </div>
                <div class="box-button">
                    <div>
                        <input class = "button" type="button" onclick="balance()" value="調整開始" id="balance_button">
                    </div>
                    <div>
                    <input class = "button" type="button" onclick="link()" value="難易度選択へ" id="m_button">
                    </div>
                </div>
            </div>
            <div id="loading">
                <div class="sk-fading-circle">
                    <div class="sk-circle1 sk-circle"></div>
                    <div class="sk-circle2 sk-circle"></div>
                    <div class="sk-circle3 sk-circle"></div>
                    <div class="sk-circle4 sk-circle"></div>
                    <div class="sk-circle5 sk-circle"></div>
                    <div class="sk-circle6 sk-circle"></div>
                    <div class="sk-circle7 sk-circle"></div>
                    <div class="sk-circle8 sk-circle"></div>
                    <div class="sk-circle9 sk-circle"></div>
                    <div class="sk-circle10 sk-circle"></div>
                    <div class="sk-circle11 sk-circle"></div>
                    <div class="sk-circle12 sk-circle"></div>
                </div>
                <div class="text">
                    <p>しばらくお待ちください</p>
                </div>
            </div>
            <footer>
                <p>Produced by MML</p>
            </footer>
        </div>
    </body>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== "") {
                var cookies = document.cookie.split(";");
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) === name + "=") {
                        cookieValue = decodeURIComponent(
                            cookie.substring(name.length + 1)
                        );
                    break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie("csrftoken");

        function csrfSafeMethod(method) {
            return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method);
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            },
        });

        window.onload = function(){
            $.ajax({
                url: '{% url "app:get_data" %}',
                type: "POST",
                data: { type: "cnn", user: userName },
                dataType: "json",
            }).done(function (data) {
                if (data["cnn"]) {
                    document.getElementById("m_button").style.visibility = 'visible';
                } else {
                    document.getElementById("m_button").style.visibility = 'hidden';
                }
                console.log(data);
            });
        }

        const loading = document.querySelector('#loading');
        loading.classList.add('hide');

        var query2 = location.search;
        var value2 = query2.split('=');

        var userName = value2[1];


        document.getElementById("balance_button").disabled = true;


        let cnt;

        function send_img_0() {
            fd.set("type", "train-0");
            fd.set("user", userName);
            $.ajax({
                url: '{% url "app:get_data" %}',
                type: "POST",
                data: fd,
                processData: false,
                contentType: false,
                dataType: "json",
            }).done(function (data) {
                cnt++;
            });
        }

        var send_cnt = 0;
        $("#send_button").on("click", function (e) {
            if (document.getElementById("send_button").disabled === false) {
                document.getElementById("send_button").setAttribute("disabled", true);
            }
            cnt = 0;
            send_cnt++;
            if (send_cnt < 7) {
                const intervalId = setInterval(() =>{
                send_img_0();
                if(cnt >= 5){
                    clearInterval(intervalId);
                    if (document.getElementById("send_button").disabled === true && send_cnt < 6) {
                    document.getElementById("send_button").removeAttribute("disabled");
                    }
                }}, 200);
                check_clear();
            }
        });


        function send_img_1() {
            fd.set("type", "train-1");
            fd.set("user", userName);
            $.ajax({
                url: '{% url "app:get_data" %}',
                type: "POST",
                data: fd,
                processData: false,
                contentType: false,
                dataType: "json",
            }).done(function (data) {
                cnt++;
            });
        }

        function check_clear()
        {
            if(send_cnt >= 6 && key_cnt >= 6)
            {
                document.getElementById("balance_button").disabled = false;
            }
        }


        var key_cnt = 0;
        document.addEventListener('keypress', keypress_ivent);
        function keypress_ivent(e) {
            cnt = 0;
            key_cnt++;
            if (key_cnt < 7) {
                const intervalId = setInterval(() =>{
                send_img_1();
                if(cnt >= 5){
                clearInterval(intervalId);
                }}, 200);
                check_clear();
            }
        }


        $(window).on('beforeunload', function() {
            $.ajax({
                url: '{% url "app:get_data" %}',
                type: "POST",
                data: { type: "close", user: userName },
                dataType: "json",
            }).done(function (data) {
                console.log(data);
            });
        });


        function balance()
        {
            loading.classList.remove('hide');
            document.getElementById("balance_button").disabled = true;
            document.getElementById("send_button").disabled = true;
            $.ajax({
                url: '{% url "app:get_data" %}',
                type: "POST",
                data: {type: "training", user: userName},
                dataType: "json",
            }).done(function (data) {
                if (data["success"]) {
                    loading.classList.add('hide');
                    document.getElementById("m_button").style.visibility = 'visible';
                    document.getElementById("m_button").disabled = false;
                }
            });
        }

        function link()
        {
            var query = location.search;
            var value = query.split('=');

            var temp = value[1];

            location.href = "{% url 'app:diffsec' %}" + "?name=" + encodeURIComponent(temp);
        }



        const video = document.getElementById("video");
        navigator.mediaDevices
            .getUserMedia({
            video: true,
            audio: false,
            })
            .then((stream) => {
            video.srcObject = stream;
            video.play();
            setInterval(draw, 200);
            })
            .catch((e) => {
            console.log(e);
            });

        const canvas = document.getElementById("canvas");
        let image = document.getElementById("image");

        canvas.width = 340;
        canvas.height = 260;

        let fd = new FormData();
        function draw() {
            let ctx = canvas.getContext("2d");

            ctx.drawImage(video, 150, 210, 340, 260, 0, 0, canvas.width, canvas.height);

            let mat = cv.imread("canvas");
            cv.cvtColor(mat, mat, cv.COLOR_RGBA2GRAY, 0);
            cv.imshow("canvas", mat);
            mat.delete();


            var base64 = canvas.toDataURL("image/jpeg", 1.0);
            image.setAttribute("src", base64);

            var bin = atob(base64.replace(/^.*,/, ""));
            var buffer = new Uint8Array(bin.length);
            for (var i = 0; i < bin.length; i++) {
            buffer[i] = bin.charCodeAt(i);
            }
            var file = new File([buffer.buffer], "img.jpeg", {
            type: "image/jpeg",
            });

            fd.set("img", file);
        }
    </script>
</html>

project/templates/user.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>あなたの情報</title>
</head>
<body>
    <h1>{{user.username}}</h1>
    <p>アカウント作成日：{{user.date_joined}}</p>
    <p><a href="{% url 'other'%}">他のユーザーの情報</a></p>
    <p><a href="{% url 'logout'%}">ログアウト</a></p>
</body>

</html>